export const ORDERS_TAG = "ORDERS_TAG"
export const ORDER_TAG = "ORDER_TAG"
export const SALE_TAG = "SALE_TAG"
export const PRICE_TAG = "PRICE_TAG"
export const SALE_WITH_PERCENT_TAG = "SALE_WITH_PERCENT_TAG"